---
- name: Deploy Application with Ansible
  hosts: ansible
  become: true
  tasks:
    - name: Ensure Java is installed
      apt:
        name: openjdk-11-jdk
        state: present
    
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
    
    - name: Install Docker Python pip package
      pip:
        name: docker
    
    - name: Ensure necessary directories exist
      file:
        path: /opt/myapp
        state: directory
        owner: ansible
        group: ansible
    
    - name: Copy application artifacts
      copy:
        src: /app/application.jar
        dest: /opt/myapp/application.jar
        owner: ansible
        group: ansible
        mode: '0644'
    
    - name: Run Docker container
      docker_container:
        name: myapp-container
        image: myapp:${BUILD_ID}
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        volumes:
          - /opt/myapp/application.jar:/app/application.jar
        env:
          JAVA_OPTS: "-Xmx512m"
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "3"
